### ISSUE TITLE
Add Invitelist table to Turso

### ISSUE THREAD

**Issue by coindegen** [guminc/turso-prisma#20]
Goal is to migrate all the existing InviteLists from MongoDB to Turso, and update the schema accordingly.

this one might be tricky because we have different styles of invite lists in our DB. We also have to refactor the unbounded `addresses` array. In Mongo this is an array containing tens of thousands of addresses, which SQLite doesn't support. Do you think it's feasible to create a many-to-many relationship between Wallet and InviteList?

Moreover, we have to plan for the future where we accommodate:
- updated invite lists with more fields
- completely different styles of invite lists based on 3rd party contracts in our marketplace

For example, how hard would it be to launch one of Zodomo's contracts, or a Honeyjar contract?

To make these invites flexible, we need some kind of slug identifying the InviteList type. 

For example, a docker-compose file has to include the version number so it can be parsed properly: https://docs.docker.com/compose/compose-file/compose-file-v3/#build

In that same way we used to version our collections:

```
isArchetype: true,
contract_type: "ERC1155",
contract_version: 60
```

We similarly should version our invitelists: `type: archetype-erc721-60`.

In SQL this can be a challenge because we can either create a bunch of extra nullable columns and try to squeeze all InviteLists into one master table, or create a multitude of specialized InviteList tables depending on the type. 

---------------

This is a deeper discussion about the Contract Marketplace, but here is a possible solution:
- create a new table called Contract

```  
model Contract {
id
name
version
owner
description

invitelist_type InviteListType
invitelist_type_id
}
```

```  
model Collection {
   [remove contract_version, is_archetype, contract_type but add:]

   contract Contract
   contract_id
}
```

- create a new table called InviteListType

```
model InviteListType {
id
abi [JSON blob stored as a String]
}
```

The abi field would be a JSON.stringified version of this:

```json
[
      { "internalType": "bytes32", "name": "_key", "type": "bytes32" },
      { "internalType": "bytes32", "name": "_cid", "type": "bytes32" },
      {
        "components": [
          { "internalType": "uint128", "name": "price", "type": "uint128" },
          { "internalType": "uint32", "name": "start", "type": "uint32" },
          { "internalType": "uint32", "name": "end", "type": "uint32" },
          { "internalType": "uint32", "name": "limit", "type": "uint32" },
          { "internalType": "uint32", "name": "maxSupply", "type": "uint32" },
          { "internalType": "uint32", "name": "unitSize", "type": "uint32" },
          {
            "internalType": "address",
            "name": "tokenAddress",
            "type": "address"
          }
        ],
        "internalType": "struct Invite",
        "name": "_invite",
        "type": "tuple"
      }
    ]
```

The above ABI json info could potentially be parsed to validate inputs, and create dynamic UIs.

Make a master, one-size-fits-all InviteList table:
```
model InviteList {
id
root
address
start_time
end_time
price
delta
interval
[...etc]

invitelist_type InviteListType
raw [JSON blob stored as String, conforming to ABI]
}
```

Remove the `addresses` field from old InviteList record, and instead add each address as a row in this joining table:
```
model _WalletToInviteList {
wallet_id
invitelist_id
}
```

This is a performant way of fetching eligible invite lists for a user, on the read side. However there might be a penalty on the write side. I think this is an acceptable trade-off.

Our migration script will populate our Wallet table with every single address in the current MongoDB. Therefore, the majority of wallets in our ecosystem can be processed and added offline.

However, when a collection owner creates an invitelist with say, 4000 addresses, we're going to have to upsert any new wallets, and write 4000 rows from splinter-core. We'll probably have to test this performance, and if it's too blocking, maybe make a background job for it instead.

**Comment by coindegen** [comment]
should mirror InviteLists from Mongo

**Comment by kneelsdev** [comment]
I  like the general idea, making everything dynamic will save us a lot of headaches in the future. Storing the raw abi as a blob is a good idea. 

For the addresses array, I think there should be no problem storing it as a raw json string:
https://www.sqlite.org/limits.html

In addition to storing the raw addresses, we could also keep a wallet relationship. This could be useful for determining what lists a user is eligible for. But also, this seems like a lot of work on insert and the benefit may not be worth the added complexity (Though you likely have a better idea than I do on this). Would a backend job make sense?

**Comment by kneelsdev** [comment]
```
This is a performant way of fetching eligible invite lists for a user, on the read side. However there might be a penalty on the write side. I think this is an acceptable trade-off.

Our migration script will populate our Wallet table with every single address in the current MongoDB. Therefore, the majority of wallets in our ecosystem can be processed and added offline.

However, when a collection owner creates an invitelist with say, 4000 addresses, we're going to have to upsert any new wallets, and write 4000 rows from splinter-core. We'll probably have to test this performance, and if it's too blocking, maybe make a background job for it instead.
```

Ah just saw this edit now, looks like we had the same idea.

**Comment by coindegen** [comment]
> For the addresses array, I think there should be no problem storing it as a raw json string:
https://www.sqlite.org/limits.html

> In addition to storing the raw addresses, we could also keep a wallet relationship. This could be useful for determining what lists a user is eligible for. But also, this seems like a lot of work on insert and the benefit may not be worth the added complexity (Though you likely have a better idea than I do on this). Would a backend job make sense?

Funny you mention that, I just updated my comment. 

Storing a raw json string doesn't make sense for addresses. Every time a user visits the mint page, it does a DB request to determine which invite lists to display on the client. The way our eligible lists GET request works is we query all the invite lists for ones which contain my address. This is untenable with a JSON blob, because we'd have to deserialize it on each query.

That's why I recommended the joining table, this is very easy to query.

**Comment by kneelsdev** [comment]
> Storing a raw json string doesn't make sense for addresses. Every time a user visits the mint page, it does a DB request to determine which invite lists to display on the client. The way our eligible lists GET request works is we query all the invite lists for ones which contain my address. This is untenable with a JSON blob, because we'd have to deserialize it on each query.

> That's why I recommended the joining table, this is very easy to query.

Good point, does mongo do any indexing in the background currently? I think we can try doing this all on insert to start, once we have more info we can decide whether to do this in a backend job. backend job could be responsible for parsing raw address data and filling the _WalletToInviteList table.
